---
- name: Deploy Thoughts frontend
  hosts: master
  #become: true  # Run tasks as a privileged user (sudo) sd
  vars:
    app_dir: /home/ubuntu/Chapter10/microservices/frontend/
    compose_file: docker-compose.yml

  tasks:

    - name: Start the frontend services
      become: true
      command:
        cmd: docker-compose up -d
        chdir: "{{ app_dir }}"

    - name: Verify services are running
      command:
        cmd: docker-compose ps
        chdir: "{{ app_dir }}"
      register: compose_ps_output

    - name: Print docker-compose status
      debug:
        var: compose_ps_output.stdout