---
- name: Deploy Thoughts Backend
  hosts: master
  #become: true  # Run tasks as a privileged user (sudo)
  vars:
    app_dir: ./thoughts_backend
    compose_file: docker-compose.yml

  tasks:

    - name: Start the thoughts_backend services
      command:
        cmd: docker-compose up -d
        chdir: "{{ app_dir }}"

    - name: Verify services are running
      command:
        cmd: docker-compose ps
        chdir: "{{ app_dir }}"
      register: compose_ps_output

    - name: Print docker-compose status
      debug:
        var: compose_ps_output.stdout
